Add ability to track which posts a user likes.
GDSCUTM-CommunityProjects/UBoard pull request #64
Opened 2021-11-26 04:56 UTC by andy9775

Create a new model which tracks when a user likes/unlikes a post. Additionally, add logic to like
and unlike posts. Finally, each `Post` response includes the number of likes and whether or not the
current user liked the given post.

This is part of #38

2021-11-26 04:57 UTC, andy9775 commented
Once the report functionality is in place, `feedbackScore` should either be a virtual field (calculated based on upvotes and reports) or it should be deprecated.

2021-11-28 01:57 UTC, plausibly requested changes

2021-11-28 01:57 UTC, plausibly commented on server/routes/v1/post.ts
>  postRouter.get('/:postid', async (req: Request, res: Response) => {
getPost call should take in auth user id

2021-11-28 01:57 UTC, plausibly commented on server/routes/v1/post.ts
> +const postController = new PostController(db.Post, db.userPostLikes);
U is capital `db.UserPostLikes`

2021-11-28 05:54 UTC, plausibly approved these changes

2021-11-29 03:42 UTC, danielduong8 approved these changes

2021-11-29 04:16 UTC, gurvirsasan approved these changes

2021-11-29 05:06 UTC, merged