Implement post-editing
GDSCUTM-CommunityProjects/UBoard pull request #77
Opened 2021-12-21 05:55 UTC by plausibly

- Update frontend API to have update post PUT request
- Clicking 'Edit' when viewing (own) post will open editing UI. This has input textfields with default value of what the post is.
- Can edit and change post title, body, location, capacity
- Some error handling when invalid capacity is entered, invalid lengths, etc..

![image](https://user-images.githubusercontent.com/66292154/146878718-10c3c7d1-735c-47f5-a61d-2f98e47a6efb.png)
![image](https://user-images.githubusercontent.com/66292154/146878736-542a8e58-8b9b-4dcf-82a4-76b3ea8579ed.png)
![image](https://user-images.githubusercontent.com/66292154/146878809-35ed85c1-cbaa-466c-ba60-dd932b754057.png)
![image](https://user-images.githubusercontent.com/66292154/146878817-00de8d49-a945-409a-82f7-bf9eed7517f9.png)

2021-12-21 23:23 UTC, andy9775 requested changes
I'm curious why you didn't reuse the create post component? You should be able to update it to take the post state via props of the post being edited. From this, if `defaultState` is not undefined you could update the `create post` button text to `update post` and use the appropriate API endpoint. We've already tested all that logic, all you would need to do is write a test to ensure that when default state is passed in, the data is visible in the form fields, the text is correct for the button, and that the updatePost api endpoint is hit.

2021-12-21 23:23 UTC, andy9775 commented on client/src/components/ViewPostDialog.tsx
> +            <MenuItem onClick={() => props.toggleEdit(true)}>Edit</MenuItem>
I'm assuming `isAuth` specifies if the user created the post they are trying to delete/update? If so, lets update that variable name, seems like it's just checking of the user is logged in. Something like `userHasCreatedPost`

2021-12-21 23:23 UTC, andy9775 commented on client/src/components/ViewPostDialog.tsx
> +      console.log(form);
```suggestion

```

2021-12-23 23:27 UTC, plausibly commented
> I'm curious why you didn't reuse the create post component? You should be able to update it to take the post state via props of the post being edited. From this, if `defaultState` is not undefined you could update the `create post` button text to `update post` and use the appropriate API endpoint. We've already tested all that logic, all you would need to do is write a test to ensure that when default state is passed in, the data is visible in the form fields, the text is correct for the button, and that the updatePost api endpoint is hit.

I thought about that, but my logic was that it will look better to have textboxes in a similar format to the post view rather than opening another dialog on top of it

2021-12-25 00:34 UTC, andy9775 approved these changes

2021-12-25 05:47 UTC, plausibly commented
Requested re-review because I made slight changes after fixing merge conflicts. Just making sure I didn't break anything.

Also @andy9775, how do we want to handle editing capacity? I was thinking they cannot reduce capacity below the amount of people that have already checked in

2021-12-25 06:29 UTC, andy9775 commented
Sounds good. Again, lets focus on getting the things we set out complete before getting deep into all the different edge cases - we could spend days on one feature, thinking of all the possible edge cases and so on.

2021-12-25 06:31 UTC, andy9775 approved these changes

2021-12-25 23:12 UTC, merged