(draft)
GDSCUTM-CommunityProjects/UBoard pull request #98
Opened 2021-12-31 20:10 UTC by plausibly

2022-01-01 02:08 UTC, plausibly commented
NOTE: FIX ANCHOR ID

2022-01-02 05:13 UTC, andy9775 approved these changes

2022-01-03 02:02 UTC, danielduong8 commented
the polling issue you are experiencing will be resolved with the fix/polling pr

2022-01-03 03:23 UTC, danielduong8 requested changes
couple small fixes, but lgtm, merge afterwards

2022-01-03 03:23 UTC, danielduong8 commented on client/src/components/PostComment.tsx
> +          setMsg('Failed to delete comment.');
write the error message in `res` to console so we have an easier time debugging

2022-01-03 03:23 UTC, danielduong8 commented on client/src/components/PostComment.tsx
> +        setMsg('Failed to delete comment. ');
same here as well but with `err`

2022-01-03 10:09 UTC, danielduong8 approved these changes

2022-01-03 10:10 UTC, merged